notify = true
shuffle = true
repeat = "playlist"
cover_max_scale = 0.0
hide_display_names = true
[theme]
background = "default"
primary = "#c0caf5"
secondary = "#7dcfff"
title = "#e0af68"
playing = "#7dcfff"
playing_selected = "#73daca"
playing_bg = "#1a1b26"
highlight = "#73daca"
highlight_bg = "#1a1b26"
error = "#c0caf5"
error_bg = "#f7768e"
statusbar = "#24283b"
statusbar_progress = "#73daca"
statusbar_bg = "#7dcfff"
cmdline_bg = "#24283b"
search_match = "#bb9af7"
